# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGAU-jgrHY4bEh6UHhz0wm6cxEuqTnsq
"""

import streamlit as st
import numpy as np
from PIL import Image
import tensorflow as tf

# Load the model
MODEL = tf.keras.models.load_model("models/2.keras")
CLASS_NAMES = ["Early Blight", "Late Blight", "Healthy"]

def read_file_as_image(data) -> np.ndarray:
    return np.array(Image.open(data))

st.title("Plant Disease Prediction")
st.write("Upload an image of a plant leaf to predict its condition.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # Process the image
    image_array = read_file_as_image(uploaded_file)
    image_batch = np.expand_dims(image_array, 0)

    # Predict
    prediction = MODEL.predict(image_batch)
    predicted_class = CLASS_NAMES[np.argmax(prediction[0])]
    confidence = np.max(prediction[0])

    # Display results
    st.write(f"Predicted Class: {predicted_class}")
    st.write(f"Confidence: {confidence:.2f}")